theme: minima
title: Shanna's Slipbox
author: from Shanna
description: Let's see what happens.

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%a, %b %-d, %Y"

header_pages:
  - about.md
  - ../one_pagers/test-page.md

