---
layout: home
list_title: "Latest Posts"
---
theme: minima
title: Shanna's Slipbox
author: "blog author"
description: A trial and error experiment in learning how to build modern websites and hosting my Obsidian vault online. from Shanna - shannaseigel@twitter
show_excerpts: false # set to true to show excerpts on the homepage
github_username: your_github_username
twitter_username: your_twitter_username