theme: minima
title: Shanna's Digital Brain
author: github.com/ShannaSeigel
description: Let's see what happens.

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%a, %b %-d, %Y"

header_pages:
  - about.md
# file must be in repo root to show up here

# generate social links in footer
social_links:
  twitter: ShannaSeigel
  github:  ShannaSeigel
  linkedin: ShannaSeigel
