theme: minima
title: Shanna's Slipbox
author: A trial and error experiment in learning how to build modern websites and hosting my Obsidian vault online.
description: from Shanna|
shannaseigel@twitter
show_excerpts: false # set to true to show excerpts on the homepage
