---
layout: home
list_title: "Latest Posts"
---
theme: minima
title: Shanna's Slipbox
header_pages:
  - about.md
defaults:
  - scope:
      path: ""
    values:
      author: "Shanna"

description: A trial and error experiment in learning how to build modern websites and hosting my Obsidian vault online. 