theme: minima
title: Shanna's Slipbox
author: from Shanna
description: My trial and error experiment.

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%a, %b %-d, %Y"

header_pages:
  - about.md

